import numpy as np
import time
from src.lasso.utils_lasso import *
#from ultils_TV import *


def _accept_damped_newton_step(
    A,
    b,
    alpha,
    cost,
    x_hat,
    d,
    beta,
    newton_stepsize,
    max_backtracks=25,
    min_step=1e-12,
):
  """Try a damped Newton correction.

  Returns
  -------
  x_new : np.ndarray
      Accepted iterate, or x_hat if no acceptable damped step is found.
  accepted : bool
      True iff a damped Newton correction was accepted.
  cost_new : float
      Objective value at x_new.
  """
  cost_hat = cost(A, x_hat, b, alpha)
  if not np.all(np.isfinite(d)):
    return x_hat, False, cost_hat

  step = float(newton_stepsize)
  shrink = float(beta)
  if not np.isfinite(cost_hat):
    return x_hat, False, cost_hat

  for _ in range(int(max_backtracks)):
    if step <= float(min_step):
      break
    x_trial = x_hat - step * d
    if not np.all(np.isfinite(x_trial)):
      step *= shrink
      continue

    cost_trial = cost(A, x_trial, b, alpha)
    if np.isfinite(cost_trial) and (cost_trial < cost_hat):
      return x_trial, True, cost_trial
    step *= shrink

  return x_hat, False, cost_hat


def _cost_from_residual_or_callable(A, x, b, alpha, cost, residual):
  if cost is cost_lasso:
    return 0.5 * (residual @ residual) + float(alpha) * np.abs(x).sum()
  return cost(A, x, b, alpha)


def _print_if_verbose(verbose, *args):
  if verbose:
    print(*args)


def _as_dense_matrix(M):
  if hasattr(M, "toarray"):
    return M.toarray()
  return np.asarray(M, dtype=float)


def _solve_alg5_lasso_direction(
    A,
    y,
    z,
    b,
    alpha,
    mu,
    active_tol,
    active=None,
    gram_active=None,
    grad_y=None,
):
  if active is None:
    active = np.flatnonzero(np.abs(z) >= float(alpha) - float(active_tol))
  d = np.zeros_like(z, dtype=float)
  if active.size == 0:
    return d

  if gram_active is None:
    A_active = A[:, active]
    gram_active = _as_dense_matrix(A_active.T @ A_active)
  if grad_y is None:
    grad_y = grad_f(A, y, b)

  rhs = (z + grad_y)[active]
  system = gram_active + float(mu) * np.eye(active.size)
  try:
    factor = np.linalg.cholesky(system)
    d_active = np.linalg.solve(factor.T, np.linalg.solve(factor, rhs))
  except np.linalg.LinAlgError:
    try:
      d_active = np.linalg.solve(system, rhs)
    except np.linalg.LinAlgError:
      d_active = np.linalg.lstsq(system, rhs, rcond=None)[0]

  d[active] = d_active
  return d


def Algo_Globalized_Effective_Subspace_Newton_Lasso(
    A,
    b,
    x0,
    alpha,
    max_iter,
    step_size,
    tol,
    cost=cost_lasso,
    prox=proxL1,
    approx_sol=0,
    theta=0.5,
    q=1.0,
    r=1.0,
    delta0=1.0,
    epsilon=1e-3,
    c=None,
    active_tol=None,
    max_line_search=500,
    verbose=True,
):
  """Regularized effective-subspace Newton method for Lasso.

  This implements Algorithm 5 from the draft for
  0.5 ||Ax-b||^2 + alpha ||x||_1, using the Lasso effective subspace
  generated by the boundary coordinates of the conjugate box
  [-alpha, alpha]^n.
  """
  x = np.asarray(x0, dtype=float).reshape(-1).copy()
  b = np.asarray(b, dtype=float).reshape(-1)
  approx_sol = np.asarray(approx_sol, dtype=float)
  if approx_sol.shape == ():
    approx_sol = np.zeros_like(x)
  else:
    approx_sol = approx_sol.reshape(-1)

  gram = _as_dense_matrix(A.T @ A)
  atb = np.asarray(A.T @ b, dtype=float).reshape(-1)
  active_cache = {}
  L = float(1.0 / step_size)
  # With the comparison setup step_size = 1 / ||A||_2^2, this matches
  # 1 / step_size - ||A||_2^2 / 2 without an extra spectral computation.
  curvature_margin = 0.5 * L
  if c is None:
    c = 0.25 * curvature_margin
  if c <= 0 or not np.isfinite(c):
    c = 1e-12
  if active_tol is None:
    active_tol = 1e-10 * max(1.0, float(alpha))

  cost_val = np.empty(max_iter + 1, dtype=float)
  x_k = np.empty(max_iter + 1, dtype=float)
  time_list = np.empty(max_iter + 1, dtype=float)

  r_x = A @ x - b
  cost_val[0] = _cost_from_residual_or_callable(A, x, b, alpha, cost, r_x)
  x_k[0] = np.linalg.norm(x - approx_sol)
  time_list[0] = 0.0
  start_time = time.time()

  for i in range(max_iter):
    grad_x = gram @ x - atb
    y = prox(x - step_size * grad_x, step_size * alpha)
    s = y - x
    s_norm = np.linalg.norm(s)
    stopping_criteria = s_norm / (1.0 + np.linalg.norm(x) + np.linalg.norm(r_x))

    if s_norm == 0.0 or stopping_criteria < tol:
      _print_if_verbose(verbose, f'Algo_Globalized_ES_Newton_Lasso converge in {i} iteration')
      return cost_val[:i+1].tolist(), x, i, x_k[:i+1].tolist(), time_list[:i+1].tolist()

    delta_k = min(float(delta0), s_norm ** float(r))
    z = (x - y) / step_size - grad_x
    active = np.flatnonzero(np.abs(z) >= float(alpha) - float(active_tol))
    if active.size == 0:
      mu = delta_k
      d = np.zeros_like(x)
    else:
      active_key = tuple(active.tolist())
      cached = active_cache.get(active_key)
      if cached is None:
        gram_active = gram[np.ix_(active, active)]
        lambda_min = float(np.linalg.eigvalsh(gram_active).min())
        cached = (gram_active, lambda_min)
        active_cache[active_key] = cached
      else:
        gram_active, lambda_min = cached

      mu = max(0.0, delta_k - lambda_min)
      grad_y = gram @ y - atb
      d = _solve_alg5_lasso_direction(
          A, y, z, b, alpha, mu, active_tol, active=active,
          gram_active=gram_active, grad_y=grad_y)

    r_y = A @ y - b
    Ad = A @ d

    # accepted_near_unit = False
    # if s_norm < float(epsilon):
    #   tau = min(0.5, s_norm ** float(q))
    #   beta_k = 1.0 - tau
    #   x_new = y - beta_k * d
    #   r_new = r_y - beta_k * Ad
    #   cost_new = _cost_from_residual_or_callable(A, x_new, b, alpha, cost, r_new)
    #   accepted_near_unit = (
    #       np.all(np.isfinite(x_new))
    #       and np.isfinite(cost_new)
    #       and cost_new <= cost_val[i] + 1e-12
    #   )

    #if not accepted_near_unit:
    beta_k = 1.0
    rhs_descent = cost_val[i] - float(c) * (s_norm ** 2)
    x_new = None
    r_new = None
    cost_new = np.inf
    for _ in range(int(max_line_search)):
      x_trial = y - beta_k * d
      if np.all(np.isfinite(x_trial)):
        r_trial = r_y - beta_k * Ad
        cost_trial = _cost_from_residual_or_callable(
            A, x_trial, b, alpha, cost, r_trial)
        if np.isfinite(cost_trial) and cost_trial <= rhs_descent + 1e-12:
          x_new = x_trial
          r_new = r_trial
          cost_new = cost_trial
          break
      beta_k *= float(theta)

      if x_new is None:
        x_new = y
        r_new = r_y
        cost_new = _cost_from_residual_or_callable(A, x_new, b, alpha, cost, r_new)

    time_list[i+1] = time.time() - start_time
    x_k[i+1] = np.linalg.norm(x_new - approx_sol)
    cost_val[i+1] = cost_new
    _print_if_verbose(
        verbose, 'Iteration:', i, 'Cost:', cost_val[i+1],
        'beta:', beta_k, 'active:', active.size, 'mu:', mu, 'beta_k', beta_k)

    if abs(cost_val[i+1] - cost_val[i]) < tol:
      _print_if_verbose(verbose, f'Algo_Globalized_ES_Newton_Lasso converge in {i} iteration')
      return cost_val[:i+2].tolist(), x_new, i, x_k[:i+2].tolist(), time_list[:i+2].tolist()

    x = x_new
    r_x = r_new

  _print_if_verbose(verbose, f'Algo_Globalized_ES_Newton_Lasso converge in {max_iter - 1} iteration')
  return cost_val.tolist(), x, max_iter - 1, x_k.tolist(), time_list.tolist()

# -------------------------------- ISTA --------------------------------------

def ISTA(A,b,x0,alpha,max_iter, step_size, tol, cost, prox, approx_sol = 0):
  x = x0.copy()
  AT = A.T

  cost_val = np.empty(max_iter + 1, dtype=float)
  x_k      = np.empty(max_iter + 1, dtype=float)
  time_list= np.empty(max_iter + 1, dtype=float)

  cost_val[0] = cost(A,x,b,alpha)
  x_k[0] = np.linalg.norm(x-approx_sol)
  time_list[0] = 0.0
  start_time = time.time()

  r = A @ x - b
  grad = AT @ r

  for i in range(max_iter):
    x = prox(x - step_size*grad, step_size*alpha)

    time_list[i+1] = time.time() - start_time
    x_k[i+1] = np.linalg.norm(x-approx_sol)
    cost_val[i+1] = cost(A,x,b,alpha)
    print('Iteration:', i, 'Cost:', cost_val[i+1])

    r = A @ x - b
    grad_new = AT @ r
    stopping_criteria = np.linalg.norm(x - prox(x - step_size*grad_new, step_size*alpha))/ (1 + np.linalg.norm(x) + np.linalg.norm(r))
    if stopping_criteria < tol or abs(cost_val[i+1] - cost_val[i]) < tol:
        print(f'Algo_Ista converge in {i} iteration')
        return cost_val[:i+2].tolist(), x, i, x_k[:i+2].tolist(), time_list[:i+2].tolist()
    grad = grad_new
  print(f'Algo_Ista converge in {i} iteration')
  return cost_val.tolist(), x, i, x_k.tolist(), time_list.tolist()

# ------------------------------- BT_ISTA ------------------------------------

def BT_ISTA(A,b,x0,alpha,max_iter, tol, cost, prox, approx_sol = 0):
  x = x0.copy()
  AT = A.T

  cost_val = np.empty(max_iter + 1, dtype=float)
  time_list= np.empty(max_iter + 1, dtype=float)
  x_k      = np.empty(max_iter + 1, dtype=float)

  cost_val[0] = cost(A,x,b,alpha)
  time_list[0] = 0.0
  x_k[0] = np.linalg.norm(x-approx_sol)
  start_time = time.time()

  r = A @ x - b
  grad = AT @ r

  for i in range(max_iter):
    step_size = backtracking_linesearch(A, b, x, grad, prox, alpha)

    x = prox(x - step_size*grad, step_size*alpha)

    x_k[i+1] = np.linalg.norm(x-approx_sol)
    cost_val[i+1] = cost(A,x,b,alpha)
    time_list[i+1] = time.time() - start_time
    print('Iteration:', i, 'Cost:', cost_val[i+1])

    r = A @ x - b
    grad_new = AT @ r
    stopping_criteria = np.linalg.norm(x - prox(x - step_size*grad_new, step_size*alpha))/ (1 + np.linalg.norm(x) + np.linalg.norm(r))
    if stopping_criteria < tol or abs(cost_val[i+1] - cost_val[i]) < tol:
        print(f'Algo_BT_Ista converge in {i} iteration')
        return cost_val[:i+2].tolist(), x, i, x_k[:i+2].tolist(), time_list[:i+2].tolist()
    grad = grad_new
  print(f'Algo_BT_Ista converge in {i} iteration')
  return cost_val.tolist(), x, i, x_k.tolist(), time_list.tolist()

# -------------------------------- FISTA1 ------------------------------------

def FISTA1(A, b, x0, alpha, max_iter, step_size, tol, cost, prox, approx_sol = 0):
    x = x0.copy()
    x_old = x0.copy()
    z = x0.copy()
    AT = A.T

    x_k = np.empty(max_iter + 1, dtype=float)
    cost_val = np.empty(max_iter + 1, dtype=float)
    time_list= np.empty(max_iter + 1, dtype=float)

    x_k[0] = np.linalg.norm(x-approx_sol)
    cost_val[0] = cost(A,x,b,alpha)
    time_list[0] = 0.0
    t = 1.0
    start_time = time.time()

    for i in range(max_iter):
        rz = A @ z - b
        grad = AT @ rz
        x = prox(z - step_size*grad, alpha*step_size)

        t_old = t
        t = (1 + np.sqrt(1 + 4*(t_old**2)))/2
        z = x + ((t_old - 1) / t) * (x - x_old)

        time_list[i+1] = time.time() - start_time
        x_k[i+1] = np.linalg.norm(x-approx_sol)
        cost_val[i+1] = cost(A,x,b,alpha)
        print('Iteration:', i, 'Cost:', cost_val[i+1])

        r = A @ x - b
        grad_xnew = AT @ r
        stopping_criteria = np.linalg.norm(x - prox(x - step_size*grad_xnew, step_size*alpha))/ (1 + np.linalg.norm(x) + np.linalg.norm(r))
        if stopping_criteria < tol or abs(cost_val[i+1] - cost_val[i]) < tol:
            print(f'Algo_Fista converge in {i} iteration')
            return cost_val[:i+2].tolist(), x, i, x_k[:i+2].tolist(), time_list[:i+2].tolist()
        x_old = x
    print(f'Algo_Fista converge in {i} iteration')
    return cost_val.tolist(), x, i, x_k.tolist(), time_list.tolist()

# ------------------------------- BT_FISTA1 ----------------------------------

def BT_FISTA1(A, b, x0, alpha, max_iter, tol, cost, prox, approx_sol = 0):
    x = x0.copy()
    x_old = x0.copy()
    z = x0.copy()
    AT = A.T

    x_k = np.empty(max_iter + 1, dtype=float)
    cost_val = np.empty(max_iter + 1, dtype=float)
    time_list= np.empty(max_iter + 1, dtype=float)

    x_k[0] = np.linalg.norm(x0-approx_sol)
    cost_val[0] = cost(A,x,b,alpha)
    time_list[0] = 0.0
    t = 1.0
    start_time = time.time()

    for i in range(max_iter):
        rz = A @ z - b
        grad = AT @ rz
        step_size = backtracking_linesearch(A, b, z, grad, prox, alpha)

        z = z - step_size*grad
        x = prox(z, alpha*step_size)
        x_k[i+1] = np.linalg.norm(x-approx_sol)
        t_old = t
        t = (1 + np.sqrt(1 + 4*(t_old**2)))/2
        z = x + ((t_old - 1) / t) * (x - x_old)
        cost_val[i+1] = cost(A,x,b,alpha)
        time_list[i+1] = time.time() - start_time

        r = A @ x - b
        grad_xnew = AT @ r
        stopping_criteria = np.linalg.norm(x - prox(x - step_size*grad_xnew, step_size*alpha))/ (1 + np.linalg.norm(x) + np.linalg.norm(r))
        if stopping_criteria < tol or abs(cost_val[i+1] - cost_val[i]) < tol:
            print(f'Algo_BT_Fista converge in {i} iteration')
            return cost_val[:i+2].tolist(), x, i, x_k[:i+2].tolist(), time_list[:i+2].tolist()

        x_old = x
    print(f'Algo_BT_Fista converge in {i} iteration')
    return cost_val.tolist(), x, i, x_k.tolist(), time_list.tolist()

# ----------------------------- Algo_Newton_Ista -----------------------------

def Algo_Newton_Ista(A,b,x0,alpha,max_iter, step_size, beta, newton_stepsize, tol, cost,
                     prox, subproblem_solver, newt_tol = 1e-3, approx_sol = 0,
                     newton_trigger_steps=3, newton_reject_streak_trigger=2,
                     newton_reject_cooldown=8, max_newton_backtracks=25,
                     verbose=True):
  x = x0.copy()
  AT = A.T

  cost_val = np.empty(max_iter + 1, dtype=float)
  time_list= np.empty(max_iter + 1, dtype=float)
  x_k      = np.empty(max_iter + 1, dtype=float)

  cost_val[0] = cost(A,x,b,alpha)
  time_list[0] = 0.0
  x_k[0] = np.linalg.norm(x-approx_sol)
  start_time = time.time()
  do_newton = 0
  close_count = 0
  reject_streak = 0
  newton_cooldown = 0

  r = A @ x - b
  grad = AT @ r

  for i in range(max_iter):
    x_hat = prox(x - step_size*grad, step_size*alpha)

    attempted_newton = False
    if do_newton:
      attempted_newton = True
      Gradient_map = (x-x_hat)/step_size
      y = Gradient_map - grad
      d = subproblem_solver(A,x_hat,y,b, alpha)
      x_new, accepted_newton, cost_new = _accept_damped_newton_step(
          A, b, alpha, cost, x_hat, d, beta, newton_stepsize,
          max_backtracks=max_newton_backtracks
      )
      if accepted_newton:
        reject_streak = 0
      else:
        reject_streak += 1
        if reject_streak >= int(newton_reject_streak_trigger):
          newton_cooldown = int(newton_reject_cooldown)
          reject_streak = 0
    else:
      x_new = x_hat
      cost_new = None

    r = A @ x_new - b
    grad_xnew = AT @ r
    if cost_new is None:
      cost_new = _cost_from_residual_or_callable(A, x_new, b, alpha, cost, r)
    time_list[i+1] = time.time() - start_time
    x_k[i+1] = np.linalg.norm(x_new-approx_sol)
    cost_val[i+1] = cost_new
    _print_if_verbose(verbose, 'Iteration:', i, 'Cost:', cost_val[i+1])

    if attempted_newton:
      # Cooldown: after one Newton step, re-arm only after consecutive close
      # proximal iterations again.
      do_newton = False
      close_count = 0
    else:
      if newton_cooldown > 0:
        newton_cooldown -= 1
        close_count = 0
      else:
        if np.linalg.norm(x_new - x) < newt_tol:
          close_count += 1
        else:
          close_count = 0
        if close_count >= int(newton_trigger_steps):
          do_newton = True

    x = x_new
    stopping_criteria = np.linalg.norm(x_new - prox(x_new - step_size*grad_xnew, step_size*alpha))/ (1 + np.linalg.norm(x_new) + np.linalg.norm(r))
    if stopping_criteria < tol or abs(cost_val[i+1] - cost_val[i]) < tol:
        _print_if_verbose(verbose, f'Algo_Newton_Ista converge in {i} iteration')
        return cost_val[:i+2].tolist(), x, i, x_k[:i+2].tolist(), time_list[:i+2].tolist()

    grad = grad_xnew
  _print_if_verbose(verbose, f'Algo_Newton_Ista converge in {i} iteration')
  return cost_val.tolist(), x, i, x_k.tolist(), time_list.tolist()

# --------------------------- Algo_Newton_BT_Ista ----------------------------

def Algo_Newton_BT_Ista(A,b,x0,alpha,max_iter, beta, newton_stepsize, tol, cost,
                        prox, subproblem_solver, newt_tol = 1e-3, approx_sol = 0,
                        newton_trigger_steps=3, newton_reject_streak_trigger=2,
                        newton_reject_cooldown=8, max_newton_backtracks=25,
                        verbose=True):
  x = x0.copy()
  AT = A.T

  cost_val = np.empty(max_iter + 1, dtype=float)
  time_list= np.empty(max_iter + 1, dtype=float)
  x_k      = np.empty(max_iter + 1, dtype=float)

  cost_val[0] = cost(A,x,b,alpha)
  time_list[0] = 0.0
  x_k[0] = np.linalg.norm(x-approx_sol)
  start_time = time.time()
  do_newton = 0
  close_count = 0
  reject_streak = 0
  newton_cooldown = 0

  r = A @ x - b
  grad = AT @ r

  for i in range(max_iter):
    step_size = backtracking_linesearch(A, b, x, grad, prox, alpha)
    x_hat = prox(x - step_size*grad, step_size*alpha)

    attempted_newton = False
    if do_newton:
      attempted_newton = True
      Gradient_map = (x-x_hat)/step_size
      y = Gradient_map - grad
      d = subproblem_solver(A,x_hat,y,b, alpha)
      x_new, accepted_newton, cost_new = _accept_damped_newton_step(
          A, b, alpha, cost, x_hat, d, beta, newton_stepsize,
          max_backtracks=max_newton_backtracks
      )
      if accepted_newton:
        reject_streak = 0
      else:
        reject_streak += 1
        if reject_streak >= int(newton_reject_streak_trigger):
          newton_cooldown = int(newton_reject_cooldown)
          reject_streak = 0
    else:
      x_new = x_hat
      cost_new = None

    r = A @ x_new - b
    grad_xnew = AT @ r
    if cost_new is None:
      cost_new = _cost_from_residual_or_callable(A, x_new, b, alpha, cost, r)
    time_list[i+1] = time.time() - start_time
    x_k[i+1] = np.linalg.norm(x_new-approx_sol)
    cost_val[i+1] = cost_new
    _print_if_verbose(verbose, 'Iteration:', i, 'Cost:', cost_val[i+1])

    if attempted_newton:
      do_newton = False
      close_count = 0
    else:
      if newton_cooldown > 0:
        newton_cooldown -= 1
        close_count = 0
      else:
        if np.linalg.norm(x_new - x) < newt_tol:
          close_count += 1
        else:
          close_count = 0
        if close_count >= int(newton_trigger_steps):
          do_newton = True

    x = x_new
    stopping_criteria = np.linalg.norm(x - prox(x - step_size*grad_xnew, step_size*alpha))/ (1 + np.linalg.norm(x) + np.linalg.norm(r))
    if stopping_criteria < tol or abs(cost_val[i+1] - cost_val[i]) < tol:
        _print_if_verbose(verbose, f'Algo_Newton_BT_Ista converge in {i} iteration')
        return cost_val[:i+2].tolist(), x, i, x_k[:i+2].tolist(), time_list[:i+2].tolist()

    grad = grad_xnew
  _print_if_verbose(verbose, f'Algo_Newton_BT_Ista converge in {i} iteration')
  return cost_val.tolist(), x, i, x_k.tolist(), time_list.tolist()

# -------------------------- Algo_Newton_Fista_new ---------------------------

def Algo_Newton_Fista_new(A,b,x0,alpha,max_iter, step_size, beta, newton_stepsize, tol, cost,
                          prox, subproblem_solver, newt_tol = 1e-3, approx_sol = 0,
                          newton_trigger_steps=3, newton_reject_streak_trigger=2,
                          newton_reject_cooldown=8, max_newton_backtracks=25,
                          verbose=True):
  x = x0.copy()
  z = x.copy()
  x_hat = x0.copy()
  x_old = x0.copy()
  x_k = np.empty(max_iter + 1, dtype=float)

  AT = A.T

  t = 1.0
  t_old = 1.0
  cost_val = np.empty(max_iter + 1, dtype=float)
  time_list= np.empty(max_iter + 1, dtype=float)
  start_time = time.time()
  do_newton = 0
  close_count = 0
  reject_streak = 0
  newton_cooldown = 0

  x_k[0] = np.linalg.norm(x0-approx_sol)
  cost_val[0] = cost(A,x0,b,alpha)
  time_list[0] = 0.0

  for i in range(max_iter):
    grad = AT @ (A @ z - b)
    x_hat = prox(z - step_size*grad, alpha*step_size)
    attempted_newton = False
    accepted_newton = False

    if do_newton:
      attempted_newton = True
      Gradient_map = (z-x_hat)/step_size
      y = Gradient_map - grad
      d =  subproblem_solver(A,x_hat,y,b, alpha)
      x_new, accepted_newton, cost_new = _accept_damped_newton_step(
          A, b, alpha, cost, x_hat, d, beta, newton_stepsize,
          max_backtracks=max_newton_backtracks
      )
      if accepted_newton:
        reject_streak = 0
      else:
        reject_streak += 1
        if reject_streak >= int(newton_reject_streak_trigger):
          newton_cooldown = int(newton_reject_cooldown)
          reject_streak = 0
    else:
      x_new = x_hat
      cost_new = None

    r = A @ x_new - b
    grad_xnew = AT @ r
    if cost_new is None:
      cost_new = _cost_from_residual_or_callable(A, x_new, b, alpha, cost, r)
    time_list[i+1] = time.time() - start_time
    x_k[i+1] = np.linalg.norm(x_new-approx_sol)
    cost_val[i+1] = cost_new
    _print_if_verbose(verbose, 'Iteration:', i, 'Cost:', cost_val[i+1])

    if attempted_newton:
      do_newton = False
      close_count = 0
    else:
      if newton_cooldown > 0:
        newton_cooldown -= 1
        close_count = 0
      else:
        # Use successive iterates for trigger consistency with ISTA-style rule.
        if np.linalg.norm(x_new - x) < newt_tol:
          close_count += 1
        else:
          close_count = 0
        if close_count >= int(newton_trigger_steps):
          do_newton = True

    x = x_new
    # Restart momentum when Newton step is effectively accepted or
    # when acceleration causes a temporary objective increase.
    if accepted_newton or (cost_val[i+1] > cost_val[i]):
      t = 1.0
      t_old = 1.0
      z = x.copy()
      x_old = x.copy()
    else:
      t = (0.99 + np.sqrt(1 + 4*(t_old**2)))/2
      z = x + ((t_old - 1) / t) * (x - x_old)
      x_old = x
      t_old = t

    stopping_criteria = np.linalg.norm(x - prox(x - step_size*grad_xnew, step_size*alpha))/ (1 + np.linalg.norm(x) + np.linalg.norm(r))
    if stopping_criteria < tol: #or abs(cost_val[i+1] - cost_val[i]) < tol:
        _print_if_verbose(verbose, f'Algo_Newton_Fista converge in {i} iteration')
        return cost_val[:i+2].tolist(), x, i, x_k[:i+2].tolist(), time_list[:i+2].tolist()
  _print_if_verbose(verbose, f'Algo_Newton_Fista converge in {i} iteration')
  return cost_val.tolist(), x, i, x_k.tolist(), time_list.tolist()

# ------------------------ Algo_Newton_BT_Fista_new --------------------------

def Algo_Newton_BT_Fista_new(A,b,x0,alpha,max_iter, beta, newton_stepsize, tol, cost,
                             prox, subproblem_solver, newt_tol = 1e-3, approx_sol = 0,
                             newton_trigger_steps=3, newton_reject_streak_trigger=2,
                             newton_reject_cooldown=8, max_newton_backtracks=25,
                             verbose=True):
  x = x0.copy()
  z = x.copy()
  x_hat = x0.copy()
  x_old = x0.copy()
  x_k = np.empty(max_iter + 1, dtype=float)

  AT = A.T

  t = 1.0
  t_old = 1.0
  cost_val = np.empty(max_iter + 1, dtype=float)
  time_list= np.empty(max_iter + 1, dtype=float)
  start_time = time.time()
  do_newton = 0
  close_count = 0
  reject_streak = 0
  newton_cooldown = 0

  x_k[0] = np.linalg.norm(x0-approx_sol)
  cost_val[0] = cost(A,x0,b,alpha)
  time_list[0] = 0.0

  for i in range(max_iter):
    grad = AT @ (A @ z - b)
    step_size = backtracking_linesearch(A, b, z, grad, prox, alpha)
    x_hat = prox(z - step_size*grad, alpha*step_size)
    attempted_newton = False
    accepted_newton = False

    if do_newton:
      attempted_newton = True
      Gradient_map = (z-x_hat)/step_size
      y = Gradient_map - grad
      d = subproblem_solver(A,x_hat,y,b, alpha)
      x_new, accepted_newton, cost_new = _accept_damped_newton_step(
          A, b, alpha, cost, x_hat, d, beta, newton_stepsize,
          max_backtracks=max_newton_backtracks
      )
      if accepted_newton:
        reject_streak = 0
      else:
        reject_streak += 1
        if reject_streak >= int(newton_reject_streak_trigger):
          newton_cooldown = int(newton_reject_cooldown)
          reject_streak = 0
    else:
      x_new = x_hat
      cost_new = None

    r = A @ x_new - b
    grad_xnew = AT @ r
    if cost_new is None:
      cost_new = _cost_from_residual_or_callable(A, x_new, b, alpha, cost, r)
    time_list[i+1] = time.time() - start_time
    x_k[i+1] = np.linalg.norm(x_new-approx_sol)
    cost_val[i+1] = cost_new
    _print_if_verbose(verbose, 'Iteration:', i, 'Cost:', cost_val[i+1])

    if attempted_newton:
      do_newton = False
      close_count = 0
    else:
      if newton_cooldown > 0:
        newton_cooldown -= 1
        close_count = 0
      else:
        if np.linalg.norm(x_new - x) < newt_tol:
          close_count += 1
        else:
          close_count = 0
        if close_count >= int(newton_trigger_steps):
          do_newton = True

    x = x_new
    if accepted_newton or (cost_val[i+1] > cost_val[i]):
      t = 1.0
      t_old = 1.0
      z = x.copy()
      x_old = x.copy()
    else:
      t = (0.99 + np.sqrt(1 + 4*(t_old**2)))/2
      z = x + ((t_old - 1) / t) * (x - x_old)
      x_old = x
      t_old = t

    stopping_criteria = np.linalg.norm(x - prox(x - step_size*grad_xnew, step_size*alpha))/ (1 + np.linalg.norm(x) + np.linalg.norm(r))
    if stopping_criteria < tol: # or abs(cost_val[i+1] - cost_val[i]) < tol:
        _print_if_verbose(verbose, f'Algo_Newton_BT_Fista converge in {i} iteration')
        return cost_val[:i+2].tolist(), x, i, x_k[:i+2].tolist(), time_list[:i+2].tolist()
  _print_if_verbose(verbose, f'Algo_Newton_BT_Fista converge in {i} iteration')
  return cost_val.tolist(), x, i, x_k.tolist(), time_list.tolist()
