objective:
  - TV1D[data_fit=quad,delta=0,reg=0.5]
dataset:
  - Simulated[n_samples=500,n_features=600,type_A=random,type_x=block,type_n=gaussian]
solver:
  - ADMM analysis[gamma=25.0,update_pen=False]
  - Celer synthesis
  - CondatVu analysis[eta=1.0,ratio=1.0]
  - Primal PGD analysis[alpha=1.0,use_acceleration=False]
  - Primal PGD analysis[alpha=1.0,use_acceleration=True]
  - Primal PGD synthesis[alpha=1.0,use_acceleration=True]
  - skglm synthesis
  - newton_ista
  - newton_fista
n-repetitions: 1
timeout: 120
max-runs: 50
