{
  "objective": [
    "Lasso Regression[fit_intercept=False,reg=0.1]",
    "Lasso Regression[fit_intercept=False,reg=0.01]"
  ],
  "dataset": [
    "Simulated[n_samples=500,n_features=600,rho=0]",
    "Simulated[n_samples=500,n_features=600,rho=0.6]"
  ],
  "solver": [
    "Celer",
    "cd",
    "fista",
    "ista",
    "newton_ista",
    "newton_fista",
    "skglm",
    "sklearn"
  ],
  "n-repetitions": 1,
  "timeout": 120,
  "max-runs": 50,
  "seed": 0
}
